_target_: models.base_unet.Unet

dim: 128
init_dim: null
out_dim: null
dim_mults: [1,2,4,8]
channels: 3
self_condition: False
resnet_block_groups: 8
learned_variance: False
learned_sinusoidal_cond: False
random_fourier_features: False
learned_sinusoidal_dim: 16
attn_dim_head: 32
attn_heads: 4
full_attn: [True, True, True, True]
flash_attn: False
