shared:
  _target_: torchvision.datasets.CelebA
  download: True
  root: './data/'
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: 64
      - _target_: torchvision.transforms.ToTensor


train:
  split: train

val:
  split: val